services:
  - type: web
    name: forecast-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn.conf.py
    autoDeploy: false

  - type: cron
    name: forecast-cron
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python forecast_cron.py
    schedule: "daily 00:00"
